cost_estimation:
  enabled: true
drift:
  enabled: true
  schedules:
    default:
      tag_query: ""
      schedule: daily

dirs:
  "**/module":
    when_modified:
      file_patterns: []
  "**/dev":
    tags:
      - dev
  "**/staging":
    tags:
      - staging
  "**/prod":
    tags:
      - prod

stacks:
  names:
    dev:
      tag_query: "dev"
      rules:
        auto_apply: true # Auto-apply for rapid development

    staging:
      tag_query: "staging"
      rules:
        apply_after:
          - dev # Can only apply after dev succeeds

    production:
      tag_query: "prod"
      rules:
        apply_after:
          - staging # Requires staging to be applied first

workflows:
  - tag_query: ""
    plan:
      - type: init
      - type: plan
      - type: checkov
      - type: env
        name: CONFTEST_POLICY
        cmd: ["echo", "$TERRATEAM_ROOT/policy/"]
      - type: conftest
